# Generated by Django 4.1.1 on 2022-12-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.CharField(default='you@xy-whitening.com', max_length=254),
        ),
    ]
