# Generated by Django 4.1.1 on 2022-12-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_message_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(max_length=1000),
        ),
    ]
