# Generated by Django 4.1.1 on 2022-11-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_productreviews_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
