# Generated by Django 4.1.1 on 2022-11-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productreview_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='title',
            field=models.TextField(default='Untitled'),
        ),
    ]
