# Generated by Django 4.1.1 on 2022-12-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productreview_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='title',
            field=models.TextField(),
        ),
    ]
