# Generated by Django 4.1.1 on 2022-12-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productreview_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='title',
            field=models.CharField(max_length=10000),
        ),
    ]
