# Generated by Django 4.1.1 on 2022-12-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productreview_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_level',
            field=models.IntegerField(default=10),
        ),
    ]
