# Generated by Django 4.1.1 on 2022-12-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_stock_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
